const EquipementTypeEnum = {
	VEHICULE_TERRESTRE: 'VEHICULE_TERRESTRE',
	ARMEMENT: 'ARMEMENT',
	COMMUNICATION: 'COMMUNICATION',
	MEDICAL: 'MEDICAL',
	PROTECTION: 'PROTECTION',
	LOGISTIQUE: 'LOGISTIQUE',
	GENIE: 'GENIE',
	SURVEILLANCE_RECONNAISSANCE: 'SURVEILLANCE_RECONNAISSANCE',
	SOUTIEN: 'SOUTIEN',
	INFORMATIQUE_ELECTRONIQUE: 'INFORMATIQUE_ELECTRONIQUE',
}

const EquipementStatusEnum = {
	MAINTENANCE: 'MAINTENANCE',
	ACTIF: 'ACTIF',
	INACTIF: 'INACTIF',
}

module.exports.EquipementTypeEnum = EquipementTypeEnum;
module.exports.EquipementStatusEnum = EquipementStatusEnum;
